version: "3"
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./volumes/postgres:/var/lib/postgres/data
    ports:
      - "5432:5432"
    network_mode: host

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    network_mode: host

  app:
    build: ./
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - redis
    network_mode: host
    command: yarn dev
